# -*- coding: GBK -*-
"""
功能：
"""
Chinese_name = {'Acadian_Flycatcher': "绿纹捕蝇雀",
                'American_Crow': "美洲乌鸦",
                'American_Goldfinch': "金翅雀",
                'American_Pipit': "琵琶鸟",
                'American_Redstart': "红尾鸲",
                'American_Three_toed_Woodpecker': "三趾啄木鸟",
                'Anna_Hummingbird': "朱红蜂鸟",
                'Artic_Tern': "亚热带燕鸥",
                'Baird_Sparrow': "贝氏草雀",
                'Baltimore_Oriole': "巴尔的摩金莺",
                'Bank_Swallow': "灰沙燕",
                'Barn_Swallow': "家燕",
                'Bay_breasted_Warbler': "湾胸莺",
                'Belted_Kingfisher': "带翠鸟",
                'Bewick_Wren': "布威克鹪鹩",
                'Black_Tern': "黑燕鸥",
                'Black_and_white_Warbler': "黑白林莺",
                'Black_billed_Cuckoo': "黑喙杜鹃",
                'Black_capped_Vireo': "黑顶莺雀",
                'Black_footed_Albatross': "黑足信天翁",
                'Black_throated_Blue_Warbler': "黑喉蓝林莺",
                'Black_throated_Sparrow': "黑喉麻雀",
                'Blue_Grosbeak': "蓝蜡嘴鸟",
                'Blue_Jay': "冠蓝鸦",
                'Blue_headed_Vireo': "蓝头莺雀",
                'Blue_winged_Warbler': "蓝翅虫森莺",
                'Boat_tailed_Grackle': "宽尾拟八哥",
                'Bobolink': "食米鸟",
                'Bohemian_Waxwing': "太平鸟",
                'Brandt_Cormorant': "加州鸬鹚",
                'Brewer_Blackbird': "蓝头黑鹂",
                'Brewer_Sparrow': "布氏麻雀",
                'Bronzed_Cowbird': "铜色牛鹂",
                'Brown_Creeper': "金冠戴菊鸟",
                'Brown_Pelican': "褐鹈鹕",
                'Brown_Thrasher': "褐鸫"}
